services:
  db:
    image: postgres:17
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: finance_bot
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  bot:
    build: .
    depends_on:
      - db
    env_file:
      - ./token.env
    environment:
      DATABASE_URL: postgres://user:password@db:5432/finance_bot?sslmode=disable
    command: /wait-for-it.sh db:5432 -- ./main


volumes:
  dbdata:
